# Config da app
spring.application.name=cep-service
server.port=8080

# Banco de dados PostgreSQL (via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/cepservice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL da API de CEP mockada (WireMock via Docker)
cep.api.url=http://localhost:8081

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Logs
logging.level.com.cepservice=DEBUG
logging.level.org.springframework.web.client=DEBUG
